name: rebuild-registry

permissions:
  contents: write

on:
  push:
    branches:
      - main
  schedule:
    - cron: "25 23 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:

    - uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v4

    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Install dependencies
      run: |
        uv pip install -r requirements.txt

    - name: Build registry
      run: python code.py
