name: rebuild-registry

on:
  workflow_dispatch:
  push:
    branches: ["gh-pages"]
  schedule:
    - cron: "30 23 * * *"

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
        with:
          version: "0.11.23"
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Set up Python
        run: uv python install
      - name: Install projecct
        run: |
          uv sync --all-extras --dev
      - name: Build registry
        id: build
        run: uv run python code.py
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
      - name: Repository Dispatch
        if: steps.build.outcome == 'success'
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}
          repository: getwilds/getwilds.github.io
          event-type: registry-updated
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Pages
        uses: actions/configure-pages@v6
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          # Upload entire repository
          path: "."
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
