name: rebuild-registry

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: "30 23 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:

    - uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build registry
      run: python code.py

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.2.0
      with:
        branch: gh-pages
        folder: .
